accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views

app_name = "accounts"
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

bookclublounge/urls.py
from django.urls import path

from .import views

urlpatterns=[
    path('', views.bookclubhome),
    path('bookclub/<str:name>', views.showBookclub, name='showdetail'),

]

booklounge/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.bookloungehome),
    path('my', views.my),
    path('introduce', views.introduce),

]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('booklounge/', include('booklounge.urls')),
    path('bookclublounge/', include('bookclublounge.urls')),
    path('accounts/', include('accounts.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from accounts.managers import UserManager
from bookclublounge.models import Bookclub

class User(AbstractUser):
    #장고가 지원하는 User모델 필드 외의 것 적어준다

    # username = None #username 사용하지 않는 경우
    # email = models.EmailField('', max_length=320, unique=True) # 유저 이메일 필드 로컬파트(64자리) + @ + 도메인파트(255자리) = 320
    nickname = models.CharField('', max_length=100, unique=True) # 유저 닉네임 필드
    # password = models.CharField('', max_length=100) # 유저 비밀번호 필드
    bookclubs = models.ManyToManyField(Bookclub, blank=True) #신청한 북클럽 필드, 다대다 관계

    # 이메일을 유저네임 필드로 사용
    # USERNAME_FIELD = 'email'
    # REQUIRED_FIELDS = ['nickname']
    #
    # objects = UserManager()

    def __str__(self):
        return '이메일 : ' + self.email + ", 닉네임 : " + self.nickname

bookclublounge/models.py
from django.db import models
from django.utils import timezone

class Bookclub(models.Model):
    name = models.CharField(max_length=200) # 북클럽 이름 필드
    description = models.TextField(max_length=2000) # 북클럽 세부내용 필드

    #초이스 선택옵션 추가, 인원수 3명부터 10명까지 가능
    MAXUSER_CHOICES = zip( range(3,11), range(3,11) )
    max_participate = models.IntegerField(choices=MAXUSER_CHOICES) # 북클럽 최대 참여인원 필드, choice기능 사용

    current_participate = models.IntegerField() # 북클럽 현재 참여인원 필드

    #초이스 선택옵션 추가, ON -> 온라인 북클럽, OFF ->오프라인 북클럽
    ONOFFLINE_CHOICES = (('ON', '온라인'),
                         ('OFF', '오프라인'))
    on_offline = models.CharField(max_length=3, choices=ONOFFLINE_CHOICES) # 북클럽 온오프라인 여부 필드, choice기능 사용

    pub_date = models.DateTimeField('date published')

booklounge/models.py
from django.db import models

accounts/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

#유저정보 가입폼
class SignupForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("username", "email", "nickname")


# 유저정보 로그인폼
class LoginForm(forms.ModelForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ("email", "password")

        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'password': forms.PasswordInput(
                attrs={
                    'class': 'form-control'
                }
            )
        }
        
#유저정보 수정폼
class UpdateForm(UserChangeForm):

    class Meta:
        model = User
        fields = ("username", "email", "nickname")

accounts/views.py
from django.contrib.auth import authenticate
from django.shortcuts import render, redirect

from accounts.models import User
from accounts.forms import SignupForm

def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=email, password=raw_password)  # 사용자 인증
            login(request, user)
        return redirect('/booklounge')
    else:
        form = SignupForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login(request):
    if request.method == "GET":
        return render(request, 'accounts/login.html')
    elif request.method == "POST":
        context = {}

        email = request.POST.get('email')
        password = request.POST.get('password')

        # 로그인 체크하기
        loginCheck = User.objects.filter(email=email, password=password).first()
        print(email + '/' + password)
        print(loginCheck)

        # 이메일, 비밀번호 입력창 공백

        # 올바른 입력
        if loginCheck is not None:

            # 로그인 정보 세션 저장
            request.session['email'] = email
            request.session['nickname'] = loginCheck.nickname

            context['email'] = email
            context['nickname'] = loginCheck.nickname
            context['message'] = loginCheck.nickname + "님이 로그인하셨습니다."
            return render(request, 'booklounge/bookloungehome.html', context)

        # 회원정보 없음
        else:

            context['message'] = "회원정보가 없습니다"
            return render(request, 'accounts/login.html', context)
# def signup(request):
#     if request.method == "GET":
#         return render(request, 'accounts/signup.html')
#     elif request.method == "POST":
#         context = {}
#         email = request.POST["email"]
#         nickname = request.POST["nickname"]
#         password = request.POST["password"]
#         passwordconfirm = request.POST["passwordconfirm"]
#         name = request.POST["name"]
#
#
#         # 이메일, 닉네임, 비밀번호 입력창 공백입력
#         if email=='' or password=='':
#             context['message'] = "필수 항목을 입력하세요."
#             return render(request, 'accounts/signup.html', context)
#
#         # 이메일 형식 벗어남
#
#         # 닉네임 형식 벗어남
#         # 비밀번호 형식 벗어남
#         # 이메일 중복
#         signupEmail = User.objects.filter(email=email)
#         if signupEmail.exists():
#             context['message'] = "사용중인 이메일입니다."
#             return render(request, 'accounts/signup.html', context)
#
#         # 닉네임 중복
#         # 비밀번호 입력과 비밀번호 확인 입력이 다름
#
#         else:
#             User.objects.create(
#                 email=email, nickname=nickname, password=password, usage_flag='y')
#             context['message'] = name + "님 회원가입 되었습니다."
#             return render(request, 'booklounge/bookloungehome.html', context)
        





def logout(request):
    request.session.flush()
    return redirect('/booklounge/')

bookclublounge/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from .models import Bookclub

def bookclubhome(request):
    bookclub_list = Bookclub.objects.order_by('-pub_date')
    # 딕셔너리 변환
    list = {'bookclub_list': bookclub_list} # {'템플릿에서 읽을 변수명':정렬한 변수명}
    return render(request, 'bookclublounge/bookclubloungehome.html', list)

def showBookclub(request, name):
    if name is not None:
        bookclub = get_object_or_404(Bookclub, name=name)
        return render(request, 'bookclublounge/bookclub.html', {'bookclub': bookclub})

# def login(request):
#     if request.method == 'POST': #요청이 post인 경우
#         form = userForm(request.POST) #요청 데이터를 userForm객체에 넣는다
#         if form.is_valid(): #폼의 데이터가 유효하다면
#             form.save() #폼의 데이터를 db의 필드별로 저장
#     else:
#             form = userForm() #post요청이 아닌 경우 단순 폼 출력
#
#     return render(request, 'booklounge/login.html', {'form': form})

booklounge/views.py
from django.shortcuts import render

def bookloungehome(request):
    context = {}

    # user세션 존재한다면 넘겨주기, 없다면 공백
    context['nickname'] = request.session.get('nickname', '')

    return render(request, 'booklounge/bookloungehome.html', context)


# def login(request):
#     if request.method == 'POST': #요청이 post인 경우
#         form = userForm(request.POST) #요청 데이터를 userForm객체에 넣는다
#         if form.is_valid(): #폼의 데이터가 유효하다면
#             form.save() #폼의 데이터를 db의 필드별로 저장
#     else:
#             form = userForm() #post요청이 아닌 경우 단순 폼 출력
#
#     return render(request, 'booklounge/login.html', {'form': form})
#
#
# def signup(request):
#     if request.method == 'POST': #요청이 post인 경우
#         form = signupForm(request.POST)
#         if form.is_valid():
#             form.save()
#     else:
#             form = signupForm() #post요청이 아닌 경우 단순 폼 출력
#
#     return render(request, 'booklounge/signup.html', {'form': form})


def my(request):

    return render(request, 'booklounge/mypage.html')


def introduce(request):

    return render(request, 'booklounge/introduce.html')

templates/accounts/login.html
{% extends 'base.html' %} <!-- 헤더부분 -->
    {% load static %}
    {% block content %}
    <main class="form-signin container text-center" style="margin-top: 300px";>
      <form method="post" action="{% url 'accounts:login' %}">
          {% csrf_token %}
        <img class="mb-4" src="{% static 'images/book.png' %}" alt="" width="72" height="57">
        <h1 class="h3 mb-3 fw-normal">로그인</h1>
        <div class="form-floating">
          <input type="email" class="form-control" id="floatingEmail" placeholder="name@example.com">
          {{ form.username.label_tag }}
        </div>
        <div class="form-floating">
          <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
          {{ form.password.label_tag }}
        </div>
          <!-- 폼 오류 출력 html -->
          {% include "form_errors.html" %}
        <div class="row justify-content-evenly" style="margin-top: 20px; margin-bottom: 229px;">
            <div class="col-4">
              <button class="w-100 btn btn-lg btn-primary" type="submit">로그인</button>
            </div>
            <div class="col-4">
              <a type="button" class="w-100 btn btn-lg btn-primary" href="{% url 'accounts:signup' %}">회원가입</a>
            </div>
        </div>
      </form>
    </main>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %} <!-- 헤더부분 -->
{% load static %}
{% block content %}
        <!-- 회원가입 폼 -->
    <main class="form-signin container text-center" style="margin-top: 300px";>
      <form method="post">
       {% csrf_token %}
        <img class="mb-4" src="{% static 'images/book.png' %}" alt="" width="72" height="57">
        <h1 class="h3 mb-3 fw-normal">회원가입</h1>

        <div class="form-floating">
            <input type="email" class="form-control" id="floatingInputEmail" placeholder="email"
                value="{{ form.email.value|default_if_none:'' }}">
            <label for="floatingInputEmail">이메일</label>
        </div>
        <div class="form-floating">
            <input type="nickname" class="form-control" id="floatingInputNickname" placeholder="nickname"
                value="{{ form.nickname.value|default_if_none:'' }}">
            <label for="floatingInputNickname">닉네임</label>
        </div>
        <div class="form-floating">
            <input type="password" class="form-control" id="floatingPassword" placeholder="Password"
                value="{{ form.password1.value|default_if_none:'' }}">
            <label for="floatingPassword">비밀번호</label>
        </div>
        <div class="form-floating">
            <input type="passwordconfirm" class="form-control" id="floatingPasswordConfirm" placeholder="Password confirm"
                value="{{ form.password2.value|default_if_none:'' }}">
            <label for="floatingPasswordConfirm">비밀번호 확인</label>
        </div>
          {% include "form_errors.html" %}
        <div class="col-4 ">
            <!--북라운지에서 회원가입하는 경우, 북클럽라운지에서 회원가입 하는 경우 나누어서 로직짜야함 -->
          <button type="submit" class="w-100 btn btn-lg btn-primary" style="margin-bottom:113px;">회원가입</button>
        </div>
      </form>
    </main>
{% endblock %}

templates/base.html
{% include "header.html" %}
{% block content %}
{% endblock %}
{% include "footer.html" %}

templates/bookclublounge/bookclub.html
    {% extends 'base.html' %} <!-- 헤더부분 -->
    {% load static %}
    {% block content %}
        <!-- 북클럽 세부정보 -->
        <section class="py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">
                    <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{% static 'images/book.png' %}" alt="..." /></div>
                    <div class="col-md-6">
<!--                        <div class="small mb-1">카테고리?</div>-->
                        <h1 class="display-5 fw-bolder">{{ bookclub.name }}</h1>
                        <div class="fs-5 mb-5">
                            <span>{{ bookclub.get_on_offline_display}}</span>
                            <span>참여 {{ bookclub.max_participate }}/{{ bookclub.current_participate }}</span>
                        </div>
                        <p class="lead">{{ bookclub.description }}</p>
                        <div class="d-flex">
                            <button class="btn btn-outline-dark flex-shrink-0" type="button">
                                참여하기
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </section>
{% endblock %}

templates/bookclublounge/bookclubhome.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Shop Item - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}"  />
       <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top shadow-sm" id="mainNav" style="height: 90px;">
            <div class="container px-5">
                <a class="navbar-brand fw-bold" href="#page-top"><span style="font-size: 70%;">Bookclub</span>Lounge</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="bi-list"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto me-4 my-3 my-lg-0">
                        <li class="nav-item"><a class="nav-link me-lg-3" href="/booklounge">북 라운지</a></li>
                    </ul>
<!--                    <button class="btn btn-primary rounded-pill px-3 mb-2 mb-lg-0" data-bs-toggle="modal" data-bs-target="#feedbackModal">-->
                        <button type="button" class="btn btn-primary rounded-pill px-3 mb-2 mb-lg-0 align-items-center" onclick="location.href='login'">로그인</button>
                </div>
            </div>
        </nav>
        <!-- 북클럽 리스트-->
        <section class="py-5 bg-light">
            <div class="container px-4 px-lg-5 mt-5">
                <h2 class="fw-bolder mb-4">북클럽 리스트</h2>
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% if bookclub_list %}
                        {% for bookclub in bookclub_list %}
                            <div class="col mb-5">
                                <div class="card h-100">
                                    <!-- 북클럽 썸네일-->
                                    <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                                    <!-- 북클럽 -->
                                    <div class="card-body p-4">
                                        <div class="text-center">
                                            <!-- 북클럽 이름 -->
                                            <h5 class="fw-bolder"><a href="/mysite/{{ bookclub.id }}/">{{ bookclub.name }}</a></h5>
                                            <!-- 북클럽 상세정보 -->
                                            {{ bookclub.description}}<br>
                                            참여 {{ bookclub.max_participate}}/ {{ bookclub.current_participate }}<br>
                                            <b>{{ bookclub.get_on_offline_display}}</b> 참여<br>
                                        </div>
                                    </div>
                                    <!-- 참여하기 버튼 -->
                                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">참여하기</a></div>
                                    </div>
                                </div>
                            </div>
                    {% endfor %}
                       {% else %}
                        <p>현재 개설된 북클럽이 없습니다.</p>
                       {% endif %}


                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
        </footer>
    </body>
</html>

templates/bookclublounge/bookclubloungehome.html
    {% extends 'base.html' %} <!-- 헤더부분 -->
    {% load static %}
    {% block content %}
        <!-- 북클럽 리스트-->
        <section class="py-5 bg-light">
            <div class="container px-4 px-lg-5 mt-5">
                <h2 class="fw-bolder mb-4">북클럽 리스트</h2>
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% if bookclub_list %}
                        {% for bookclub in bookclub_list %}
                            <div class="col mb-5">
                                <div class="card h-100">
                                    <!-- 북클럽 썸네일-->
                                    <img class="card-img-top" src="{% static 'images/book.png' %}" alt="..." />
                                    <!-- 북클럽 -->
                                    <div class="card-body p-4">
                                        <div class="text-center">
                                            <!-- 북클럽 이름 -->
                                            <h5 class="fw-bolder">{{ bookclub.name }}</h5>
                                            <!-- 북클럽 설명 -->
                                            <div class="des">{{ bookclub.description | truncatewords:30 }}<br></div>
                                            <!-- 최대 참여인원/현재 참여인원 -->
                                            참여 {{ bookclub.max_participate}}/ {{ bookclub.current_participate }}<br>
                                            <!-- 오프라인, 온라인 여부 -->
                                            <b>{{ bookclub.get_on_offline_display}}</b> 참여<br>
                                        </div>
                                    </div>
                                    <!-- 참여하기 버튼 -->
                                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'showdetail' bookclub.name %}">참여하기</a></div>
                                    </div>
                                </div>
                            </div>
                    {% endfor %}
                       {% else %}
                        <p>현재 개설된 북클럽이 없습니다.</p>
                       {% endif %}
                </div>
            </div>
        </section>
{% endblock %}

templates/footer.html
        <footer class="bg-black text-center py-5">
            <div class="container px-5">
                <div class="text-white-50 small">
                    <div class="mb-2">&copy; Your Website 2022. All Rights Reserved.</div>
                    <a href="#!">Privacy</a>
                    <span class="mx-1">&middot;</span>
                    <a href="#!">Terms</a>
                    <span class="mx-1">&middot;</span>
                    <a href="#!">FAQ</a>
                </div>
            </div>
        </footer>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

templates/form_errors.html
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 값 누락, 형식 불일치 등 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 필드와 상관없는 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/header.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <title>
                {% if '/booklounge' in request.path %}
                    booklounge
                {% elif '/bookclublounge/bookclub' in request.path %}
                    {{ bookclub.name }}
                {% elif '/bookclublounge' in request.path %}
                    bookclublounge

                {% endif %}</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}"  />
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'styles_v6.0.6.css' %}"  />

        <style>
            <!-- footer 하단 고정 css -->
            html, body {
              height: 100%;
            }

            .wrapper {
              position: relative;
              min-height: 100%;
            }

            .footer {
              position: absolute;
              bottom: 0;
            }
            <!-- 북라운지 관련 css -->
            #book1{
              width: 60%;
              height: 50%;
            }

            #slied{
                height:500px;
            }

            #slied_contents{
                height:400px;
            }

            .img-thumbnail{
                height:300px;
                width:400px;
            }


        </style>
    </head>

    <body id="page-top">
    <div class="wrapper">
        <nav class="navbar navbar-expand-lg navbar-light fixed-top shadow-sm" id="mainNav" >
            <div class="container px-5">
                {% if '/booklounge' in request.path %}
                    <a class="navbar-brand fw-bold" href="#page-top">Booklounge</a>
                {% elif '/account' in request.path %}
                    <a class="navbar-brand fw-bold" href="/booklounge">Booklounge</a>
                {% elif '/bookclublounge' in request.path %}
                    <a class="navbar-brand fw-bold" href="/bookclublounge"><span style="font-size: 70%;">Bookclub</span>lounge</a>
                {% endif %}

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="bi-list"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto me-4 my-3 my-lg-0">
                        <li class="nav-item">
                            {% if '/booklounge' in request.path %}
                            <a class="nav-link me-lg-3" href="/bookclublounge">북클럽 라운지</a>
                            {% elif '/bookclublounge' in request.path %}
                            <a class="nav-link me-lg-3" href="/booklounge">북 라운지</a>
                            {% endif %}
                        </li>
                        {% if user.is_authenticated %}
                         <li class="nav-item">
                             <a class="nav-link" href="{% url 'accounts:logout' %}">{{ user.nickname }} 로그아웃</a></li>
                         {% else %}
                         <li class="nav-item">
                            <a type="button" class="btn btn-primary rounded-pill px-3 mb-2 mb-lg-0 align-items-center" href="{% url 'accounts:login' %}?next={{ request.path }}">로그인</a>
                         </li>
                         {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </div>

templates/mysite/content_list.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Shop Item - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}"  />
       <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Related items section-->
        <section class="py-5 bg-light">
            <div class="container px-4 px-lg-5 mt-5">
                <h2 class="fw-bolder mb-4">북클럽 리스트</h2>
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% if content_list %}
                        {% for content in content_list %}
                            <div class="col mb-5">
                                <div class="card h-100">
                                    <!-- book image-->
                                    <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                                    <!-- Product details-->
                                    <div class="card-body p-4">
                                        <div class="text-center">
                                            <!-- Product name-->
                                            <h5 class="fw-bolder"><a href="/mysite/{{ content.id }}/">{{ content.title }}</a></h5>
                                            <!-- Product price-->
                                            {{ content.content}}<br>온라인
                                        </div>
                                    </div>
                                    <!-- Product actions-->
                                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">참여하기</a></div>
                                    </div>
                                </div>
                            </div>
                    {% endfor %}
                       {% else %}
                        <p>content 가 없습니다.</p>
                       {% endif %}


                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p></div>
        </footer>
    </body>
</html>